sara_shield_controller:
    type: franka_sara_shield_controller/SaraShieldController
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
sara_shield_impedance_controller:
    type: franka_sara_shield_controller/SaraShieldImpedanceController
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    k_gains:
        - 300.00
        - 300.00
        - 300.00
        - 300.00
        - 100.00
        - 50.0
        - 50.0
    d_gains:
        - 60.00
        - 60.00
        - 60.00
        - 60.00
        - 10.00
        - 5.0
        - 5.0
    translational_stiffness: 60.0
    rotational_stiffness: 3.0
    nullspace_stiffness: 10.0
    publish_rate: 500.0
    coriolis_factor: 1.0