robot_name: "panda"

# Failsafe information
max_s_stop: 0.2
q_min_allowed: [-2.3, -1.5, -2.4837, -2.7378, -2.4700, 0.8421, -2.6795]
q_max_allowed: [2.3, 1.5, 2.4837, -0.4561, 2.4700, 4.2, 2.6795]
v_max_allowed: [2.0, 1.0, 2.0, 1.25, 3.00, 1.50, 3.00]
a_max_allowed: [20, 20, 20, 20, 20, 20, 20]
j_max_allowed: [400, 400, 400, 400, 400, 400, 400]
# Maximum long-term planning acc / jerk
a_max_ltt: [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]
j_max_ltt: [15, 15, 15, 15, 15, 15, 15]

nb_joints: 7

q1: [0.0]
q2: [0.0]
q3: [0.0]
q4: [0.0]
q5: [0.0]
q6: [0.0]
q7: [0.0]

alpha_i_max: 5.0

# safety-rated speed specified by iso-norm
v_safe: 0.1

# APPROXIMATE == 0
# EXACT == 1
velocity_method: 0